blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myblog.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/myblog/urls.py
from django.urls import path
from .views import HomeView, ArticleDetailView, AddPostView, UpdatePostView, DeletePostView, AddCategoryView, AddCommentView, category_view, category_list_view, like_view
from django.contrib.auth.decorators import login_required

app_name = 'myblog'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article-detail'),
    path('add_post/', login_required(AddPostView.as_view()), name='add-post'),
    path('add_category/', login_required(AddCategoryView.as_view()), name='add-category'),
    path('article/edit/<int:pk>/', login_required(UpdatePostView.as_view()), name='edit-post'),
    path('article/delete/<int:pk>/', login_required(DeletePostView.as_view()), name='delete-post'),
    path('category/<str:cats>/', category_view, name='category'),
    path('category-list/', category_list_view, name='category-list'),
    path('like/<int:pk>/', like_view, name='like-post'),
    path('article/<int:pk>/comment/', login_required(AddCommentView.as_view()), name='add-comment'),
]

blog/users/urls.py
from django.urls import path
from .views import UserRegisterView, CustomLoginView, CustomLogoutView, UserEditView, ChangePasswordView, ShowProfileView, EditProfilePageView, CreateProfilePageView
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'users'
urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('edit_profile/', login_required(UserEditView.as_view()), name='edit-profile'),
    path('password-change/', ChangePasswordView.as_view(template_name='registration/change_password.html'), name='change-password'),
    path('password-success/', views.password_change_success, name='password-change-success'),
    path('<int:pk>/profile/', ShowProfileView.as_view(), name='show-profile'),
    path('<int:pk>/edit_profile_page/', login_required(EditProfilePageView.as_view()), name='edit-profile-page'),
    path('create_profile_page/', login_required(CreateProfilePageView.as_view()), name='create-profile-page'),
]

blog/myblog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField

class Category(models.Model):
    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self) -> str:
        return self.name
    
    def get_absolute_url(self):
        return reverse('myblog:home')

    name = models.CharField(max_length=50)

class UserProfile(models.Model):
    class Meta:
        verbose_name_plural = 'User Profiles'

    def __str__(self) -> str:
        return self.user.username

    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio = models.TextField()
    profile_pic = models.ImageField(upload_to='images/profile/', blank=True, null=True)
    website_link = models.URLField(null=True, blank=True)
    instagram_link = models.URLField(null=True, blank=True)
    facebook_link = models.URLField(null=True, blank=True)
    twitter_link = models.URLField(null=True, blank=True)

class Post(models.Model):
    class Meta:
        verbose_name_plural ='Posts'

    def __str__(self) -> str:
        return self.title + ' | ' + self.author.username
    
    def get_absolute_url(self):
        return reverse('myblog:article-detail', args={str(self.id)})
    
    def total_likes(self):
        return self.likes.count()

    title = models.CharField(max_length=255)
    header_image = models.ImageField(blank=True, null=True, upload_to='images/')
    title_tag = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, 
                                null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    snippet = models.CharField(max_length=200)
    body = RichTextField()
    created_at = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='blog_post', blank=True, null=True)

class Comment(models.Model):
    class Meta:
        verbose_name_plural = 'Comments'

    def __str__(self) -> str:
        return f"{self.name.username} - {self.post} - {self.body}"
    
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

blog/myblog/forms.py
from django import forms
from .models import Post, Comment
from ckeditor.fields import RichTextField

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'header_image', 'category', 'title_tag', 'snippet', 'body',) 
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'title_tag': forms.TextInput(attrs={'class': 'form-control'}),
            'snippet': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)  # Retrieve user from kwargs
        super(PostForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(PostForm, self).save(commit=False)
        if self.user:
            instance.author = self.user  # Set the author to the logged-in user
        if commit:
            instance.save()
        return instance

class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'header_image', 'category', 'title_tag', 'snippet', 'body')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'title_tag': forms.TextInput(attrs={'class': 'form-control'}),
            'snippet': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.TextInput(attrs={'class': 'form-control', 
                                           'placeholder': 'Write a comment...',
                                        }
                                    ),
        }
        labels = {
            'body': 'Your Comment',
        }

blog/myblog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Category, Comment
from .forms import PostForm, EditForm, CommentForm
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect

class HomeView(ListView):
    model = Post
    template_name = 'home.html'
    ordering = ['-created_at']

    def get_context_data(self, *args, **kwargs):
        category_menu = Category.objects.all()
        context = super(HomeView, self).get_context_data(*args, **kwargs)
        context["category_menu"] = category_menu
        return context

class ArticleDetailView(DetailView):
    model = Post
    template_name = 'article_details.html'

    def get_context_data(self, *args, **kwargs):
        category_menu = Category.objects.all()
        context = super(ArticleDetailView, self).get_context_data(*args, **kwargs)

        post = get_object_or_404(Post, id=self.kwargs['pk'])
        total_likes = post.total_likes()

        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        context["category_menu"] = category_menu
        context["total_likes"] = total_likes
        context["liked"] = liked
        return context

class AddPostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'add_post.html'
    success_url = reverse_lazy('myblog:home') 

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # Pass the logged-in user to the form
        return kwargs

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
class AddCommentView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'add_comment.html'

    def form_valid(self, form):
        # Fetch the post using the pk from the URL and assign it to the comment
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        form.instance.post = post  # Set the post field of the Comment instance
        form.instance.name = self.request.user  # Assign the current logged-in user to the name field
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = get_object_or_404(Post, pk=self.kwargs['pk'])  # Ensure the post is in the context
        return context
    
    def get_success_url(self):
        # Redirect to the article detail page after the comment is successfully added
        return reverse_lazy('myblog:article-detail', args=[str(self.object.post.pk)])

class AddCategoryView(CreateView):
    model = Category
    template_name = 'add_category.html'
    fields = '__all__'

    def form_valid(self, form):
        form.instance.name = form.instance.name.lower()
        return super().form_valid(form)

class UpdatePostView(UpdateView):
    model = Post
    form_class = EditForm
    template_name = 'edit_post.html'

class DeletePostView(DeleteView):
    model = Post
    template_name = 'delete_post.html'
    success_url = reverse_lazy('myblog:home')

def category_view(request, cats):
    category = get_object_or_404(Category, name=cats.replace('-', ' '))
    category_posts = Post.objects.filter(category=category)
    category_menu = Category.objects.all()
    context = {
        'category_posts': category_posts,
        'cats': cats.replace('-', ' '),
        'category_menu': category_menu,
    }
    return render(request, 'categories.html', context=context)

def category_list_view(request):
    category_menu_list = Category.objects.all()
    context = {
        'category_menu_list': category_menu_list
    }
    return render(request, 'category_list.html', context=context)

def like_view(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True

    return HttpResponseRedirect(reverse('myblog:article-detail', args=[str(pk)]))

blog/myblog/templates/add_category.html
{% extends "base.html" %}

{% block title %}Add Category{% endblock title %}

{% block content %}

<h1>Create New Category</h1>

<br>

<div class="col-8">
<form method="post">
{% csrf_token %}

    {{form.as_p}}
    <button class="btn btn-secondary">Post</button>

</form>
</div>

{% endblock content %}

blog/myblog/templates/add_comment.html
{% extends "base.html" %}

{% block title %}Add Comment{% endblock title %}

{% block content %}

<h1>Add Comment</h1>

<br>

<div class="col-8">
<form method="post" enctype="multipart/form-data">
{% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-secondary">Add Comment</button>
    &nbsp;
    <a href="{% url "myblog:article-detail" post.pk %}" class="btn btn-danger">Cancel</a>

</form>
</div>

{% endblock content %}

blog/myblog/templates/add_post.html
{% extends "base.html" %}

{% block title %}Add Post{% endblock title %}

{% block content %}

<h1>Create Blog Post</h1>

<br>

<div class="col-8">
<form method="post" enctype="multipart/form-data">
{% csrf_token %}
    {{form.media}}
    {{form.as_p}}
    <button class="btn btn-secondary">Post</button>
    &nbsp;
    <a href="{% url "myblog:home" %}" class="btn btn-danger">Cancel</a>

</form>
</div>

{% endblock content %}

blog/myblog/templates/article_details.html
{% extends "base.html" %}
{% load static %}

{% block title %}Article{% endblock title %}

{% block content %}

    <h1>{{post.title|title}}</h1> 

    <small>By: {{post.author.first_name|title}} {{post.author.last_name|title}} - {{post.created_at}}</small>
    
    {% if post.author.id == user.id %}
    <small><a href="{% url "myblog:edit-post" post.pk %}">Edit</a></small>
    <small><a href="{% url "myblog:delete-post" post.pk %}">Delete</a></small>
    {% endif %}

    <br>

    {% if post.category %}
    <small>Category: {{post.category|title}}</small>
    {% endif %}

    <hr>

    {% if post.header_image %}
        <img src="{{post.header_image.url}}" alt="">
    {% endif %}

    <p>{{post.body|safe}}</p>

    <br>

    {% if user.is_authenticated %}

        <form action="{% url "myblog:like-post" post.pk %}" 
        method="POST">
        {% csrf_token %}

            {% if liked %}
                <button type="submit" name="post_id"
                value="{{post.id}}" class="btn btn-primary btn-sm">
                    Unlike
                </button>
            {% else %}
                <button type="submit" name="post_id"
                value="{{post.id}}" class="btn btn-primary btn-sm">
                    Like
                </button>
            {% endif %}

            {% if total_likes <= 1 %}
            - {{total_likes}} Like
            {% else %}
            - {{total_likes}} Likes
            {% endif %}
            
        </form>

    {% endif %}

    <br>

    <a href="{% url "myblog:home" %}" class="btn btn-secondary">Back</a>

    <br><br>

    <div class="card mb-3">
        <div class="row g-0">
          <div class="col-md-2">
            {% if post.author.userprofile.profile_pic %}
                <img src="{{post.author.userprofile.profile_pic.url}}" class="img-fluid rounded-start">
            {% else %}
                <img src="{% static "myblog/images/user.jpg" %}" alt="" class="img-fluid rounded-start">
            {% endif %}
          </div>
          <div class="col-md-10">
            <div class="card-body">
                <h5 class="card-title">
                    {{post.author.first_name}} 
                    {{post.author.last_name}}
                </h5>
                <p class="small text-muted">

                    <a href="{% url "users:show-profile" post.author.userprofile.id %}" style="text-decoration: none;">Profile</a>

                    {% if post.author.userprofile.website_link %}
                        | <a href="{{post.author.userprofile.website_link}}" style="text-decoration: none;" target="_blank">Website</a>
                    {% endif %}

                    {% if post.author.userprofile.facebook_link %}
                        | <a href="{{post.author.userprofile.facebook_link}}" style="text-decoration: none;" target="_blank">Facebook</a>
                    {% endif %}

                    {% if post.author.userprofile.instagram_link %}
                        | <a href="{{post.author.userprofile.instagram_link}}" style="text-decoration: none;" target="_blank">Instagram</a>
                    {% endif %}

                    {% if post.author.userprofile.twitter_link %}
                        | <a href="{{post.author.userprofile.twitter_link}}" style="text-decoration: none;" target="_blank">Twitter</a>
                    {% endif %}

                </p>
                <p class="card-text">
                    {{post.author.userprofile.bio}}
                </p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
          </div>
        </div>
    </div>

    <br>

    <h2>Comments...</h2>
    
    <br>
    
    {% if not post.comments.all %}
    No Comments Yet
    <br><br>
    {% else %}
    {% for comment in post.comments.all %}
    <strong>{{comment.name}}</strong><br>
    {{comment.body}} - {{comment.created_at}}
    <br><br>
    {% endfor %}
    {% endif %}
    
    <a href="{% url "myblog:add-comment" post.pk %}" style="text-decoration: none;">Add comment</a>

    <br><br>


    <br><br>

{% endblock content %}

blog/myblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %} | Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
    {% include "navbar.html" %}
    <br>
    <div class="container">

        {% block content %}{% endblock content %}
    
        {% block scripts %}{% endblock scripts %}

        {% block extra_js %}
        <!-- Additional JS can go here -->
        {% endblock extra_js %}
    </div>
</body>
</html>

blog/myblog/templates/categories.html
{% extends "base.html" %}

{% block title %}Categories{% endblock title %}

{% block content %}

<h1>{{cats|title}}</h1>

<br>

{% for post in category_posts %}

<ul>
    <li>
        <a href="{% url "myblog:article-detail" post.pk %}" style="text-decoration: none;">{{post.title}}</a> 
        {% if post.category %}
            - {{post.category|title}} 
        {% endif %}
        - {{post.author.first_name|title}} {{post.author.last_name|title}}
        <!-- show these options only if the user is author -->
        {% if user.id == post.author.id%}
        <small><a href="{% url "myblog:edit-post" post.pk %}">Edit</a></small>
        <small><a href="{% url "myblog:delete-post" post.pk %}">Delete</a></small>
        {% endif %}
    </li>
</ul>

{% endfor %}

{% endblock content %}

blog/myblog/templates/category_list.html
{% extends "base.html" %}

{% block title %}Blog Categories{% endblock title %}

{% block content %}

    <h1>Blog Categories</h1>

    <br>

    {% for menu in category_menu_list %}

        <h4>
            <a href="{% url "myblog:category" menu.name|slugify %}">
                {{menu.name|title}}
            </a>
        </h4>

    {% endfor %}

{% endblock content %}

blog/myblog/templates/delete_post.html
{% extends "base.html" %}

{% block title %}Delete Post{% endblock title %}

{% block content %}

    {% if post.author.id == user.id %}

        <h1>Delete Post</h1>

        <br>

        <h3>Blog: {{post.title}}</h3>

        <br>

        <div class="col-8">
        <form method="post">
        {% csrf_token %}
            <h5>Are you sure you want to delete this post?</h5><br>
            <button class="btn btn-secondary btn-sm">Delete</button>
            &nbsp;
            <a href="{% url "myblog:home" %}" class="btn btn-danger btn-sm">Cancel</a>
        </form>
        </div>

    {% else %}

        <h3 class="text-center">This action isn't allowed</h3>

    {% endif %}

{% endblock content %}

blog/myblog/templates/edit_post.html
{% extends "base.html" %}

{% block title %}Update Post{% endblock title %}

{% block content %}

    {% if post.author.id == user.id %}

        <h1>Edit Blog Post</h1>

        <br>

        <div class="col-8">
        <form method="post">
        {% csrf_token %}
            {{form.media}}
            {{form.as_p}}
            <button class="btn btn-secondary">Update</button>
            &nbsp;
            <a href="{% url "myblog:home" %}" class="btn btn-danger">Cancel</a>
            <br><br>

        </form>
        </div>

    {% else %}

        <h3 class="text-center">This action isn't allowed</h3>

    {% endif %}

{% endblock content %}

blog/myblog/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock title %}

{% block content %}

<h1>Posts</h1>

<br>

{% for post in object_list %}

<ul>
    <li>
        <a href="{% url "myblog:article-detail" post.pk %}" style="text-decoration: none;">{{post.title}}</a> 
        {% if post.category %}
            <a href="{% url "myblog:category" post.category|slugify %}" style="text-decoration: none;">- {{post.category|title}}</a>
        {% endif %}
        - {{post.author.first_name|title}} {{post.author.last_name|title}}
        <!-- show these options only if the user is author -->
        {% if user.id == post.author.id%}
        <small><a href="{% url "myblog:edit-post" post.pk %}">Edit</a></small>
        <small><a href="{% url "myblog:delete-post" post.pk %}">Delete</a></small>
        {% endif %}
        <br>
        {{post.snippet}}
    </li>
</ul>

{% endfor %}

{% endblock content %}

blog/myblog/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'myblog:home' %}">My Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'myblog:home' %}">Home</a>
        </li>

        <!-- Category Menu -->
        {% if category_menu %}
          <li class="nav-item dropdown">
            <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for menu in category_menu %}
              <li><a class="dropdown-item" href="{% url 'myblog:category' menu.name|slugify %}">{{menu.name|title}}</a></li>
              {% endfor %}
            </ul>
          </li>
        {% else %}
          <li class="nav-item">
            <a href="{% url 'myblog:category-list' %}" class="nav-link active">
              Categories
            </a>
          </li>
        {% endif %}

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'myblog:add-post' %}">Add Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'myblog:add-category' %}">Add Category</a>
        </li>
        {% endif %}
      </ul>

      <ul class="navbar-nav ms-auto">
        {% if not user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'users:login' %}">Login</a>
          </li>
        {% else %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Profile
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              {% if user.userprofile.id %}
                <li><a class="dropdown-item" href="{% url "users:show-profile" user.userprofile.id %}">Profile</a></li>
                <li><a class="dropdown-item" href="{% url "users:edit-profile-page" user.userprofile.id %}">Edit Profile</a></li>
              {% else %}
                <li><a class="dropdown-item" href="{% url "users:create-profile-page" %}">Create Profile</a></li>
              {% endif %}
              <li><a class="dropdown-item" href="{% url 'users:edit-profile' %}">Settings</a></li>
            </ul>
          </li>

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#" 
              onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
          </li>
        {% endif %}
      </ul>

      <form id="logout-form" action="{% url 'users:logout' %}" method="post" style="display: none;">
        {% csrf_token %}
      </form>
      
    </div>
  </div>
</nav>